name: Ruby

on:
  push:
    branches: [rspec]
  pull_request:
    branches: [rspec]

env:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

jobs:
  test:
    name: Test
    environment: rails_tdd
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.4
          bundler-cache: false

      - name: Update RubyGems
        run: gem update --system 3.2.3

      - name: Install Bundler
        run: gem install bundler -v 1.17.3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get -yqq install libpq-dev
          bundle _1.17.3_ install --jobs 4 --retry 3

      - name: Copy database config
        run: cp config/database.ci.yml config/database.yml

      - name: Set up the database
        run: bundle exec rails db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          PGHOST: localhost
          DISABLE_SPRING: 1
        run: bundle exec rspec --format progress

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
